package bf.be.android.hangman.model

enum class AvatarMoods {
    FACE_HAPPY_EYES_FORWARD,
    FACE_BORED_EYES_UP_LEFT,
    FACE_BORED_EYES_UP_RIGHT,
    FACE_BORED_EYES_DOWN_LEFT,
    FACE_BORED_EYES_DOWN_RIGHT,
    FACE_DEAD,
    EYES_CLOSED,
    EYES_HAPPY_FORWARD
}